
# Copyright 2017-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


tosca_definitions_version: tosca_simple_yaml_1_0

description: Some basic fixtures

imports:
   - custom_types/xos.yaml

topology_template:
  node_templates:

    xos:
      type: tosca.nodes.XOS

# -----------------------------------------------------------------------------
# Network Parameter Types
# -----------------------------------------------------------------------------

    s_tag:
      type: tosca.nodes.NetworkParameterType

    c_tag:
      type: tosca.nodes.NetworkParameterType

    next_hop:
      type: tosca.nodes.NetworkParameterType

    device:
      type: tosca.nodes.NetworkParameterType

    bridge:
      type: tosca.nodes.NetworkParameterType

    neutron_port_name:
      type: tosca.nodes.NetworkParameterType

# ----------------------------------------------------------------------------
# Roles
# ----------------------------------------------------------------------------

    siterole#admin:
      type: tosca.nodes.SiteRole

    siterole#pi:
      type: tosca.nodes.SiteRole

    siterole#tech:
      type: tosca.nodes.SiteRole

    deploymentrole#admin:
      type: tosca.nodes.DeploymentRole

    slicerole#admin:
      type: tosca.nodes.SliceRole

    slicerole#access:
      type: tosca.nodes.SliceRole

# -----------------------------------------------------------------------------
# Flavors
# -----------------------------------------------------------------------------

    m1.small:
      type: tosca.nodes.Flavor

    m1.medium:
      type: tosca.nodes.Flavor

    m1.large:
      type: tosca.nodes.Flavor

    m1.xlarge:
      type: tosca.nodes.Flavor

# -----------------------------------------------------------------------------
# Network Templates
# -----------------------------------------------------------------------------

    Private:
      type: tosca.nodes.NetworkTemplate
      properties:
        visibility: private
        translation: none

    Public shared IPv4:
      type: tosca.nodes.NetworkTemplate
      properties:
        visibility: private
        translation: NAT
        shared_network_name: nat-net

    Public dedicated IPv4:
      type: tosca.nodes.NetworkTemplate
      properties:
        visibility: public
        translation: none
        shared_network_name: ext-net

