- name: Install nsd
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - nsd

- name: Ensure that zones directory exists
  file:
    name: "{{ nsd_zonesdir }}"
    state: directory
    mode: 0755
    owner: root
    group: "{{ nsd_group }}"

- name: Create nsd.conf from template
  template:
    src: nsd.conf.j2
    dest: "{{ nsd_conf }}"
    mode: 0644
    owner: root
    group: "{{ nsd_group }}"

- name: create forward zonefiles from template
  template:
    src: zone.forward.j2
    dest: "{{ nsd_zonesdir }}/{{ item.name }}.forward"
    mode: 0644
    owner: root
    group: "{{ nsd_group }}"
  with_items: "{{ nsd_zones }}"

- name: create reverse zonefiles from template
  template:
    src: zone.reverse.j2
    dest: "{{ nsd_zonesdir }}/{{ item.name }}.reverse"
    mode: 0644
    owner: root
    group: "{{ nsd_group }}"
  with_items: "{{ nsd_zones }}"

- name: reload-nsd
  service:
    name: nsd
    enabled: yes
    state: reloaded

- name: restart-nsd
  service:
    name: nsd
    enabled: yes
    state: restarted

