ovs_bridges:
  - leaf1
#  - leaf2
  - spine1
#  - spine2

ovs_patch_ports:
  - { bridge: leaf1, port: leaf1-spine1, peer: spine1-leaf1 }
#  - { bridge: leaf2, port: leaf2-spine1, peer: spine1-leaf2 }
#  - { bridge: leaf1, port: leaf1-spine2, peer: spine2-leaf1 }
#  - { bridge: leaf2, port: leaf2-spine2, peer: spine2-leaf2 }
  - { bridge: spine1, port: spine1-leaf1, peer: leaf1-spine1 }
#  - { bridge: spine2, port: spine2-leaf1, peer: leaf1-spine2 }
#  - { bridge: spine1, port: spine1-leaf2, peer: leaf2-spine1 }
#  - { bridge: spine2, port: spine2-leaf2, peer: leaf2-spine2 }

enable_fabric: False

ovs_controller_ip: 10.100.198.201
ovs_controller_port: 6653

ovs_packages:
  - openvswitch-switch
  - openvswitch-common

ovs_fabric_packages:
  - name: openvswitch-common_2.5.3-1_amd64.deb
    url: http://www.vicci.org/openvswitch-2.5.3/openvswitch-common_2.5.3-1_amd64.deb
    checksum: sha256:30c159c4a13d4eab75acdb04dca7acc0beee5dd0465b1b5b2e31a3a625e4c248
  - name: openvswitch-switch_2.5.3-1_amd64.deb
    url: http://www.vicci.org/openvswitch-2.5.3/openvswitch-switch_2.5.3-1_amd64.deb
    checksum: sha256:b68e63f6408e1392bb0457760c77189c9b3380e1b354fdaec17e119e09ab5db6
