- name: Include variables
  include_vars: "{{ item }}"
  with_items:
    - "{{ cord_workdir }}/build/platform-install/profile_manifests/{{ cord_profile }}.yml"
    - "{{ cord_workdir }}/build/platform-install/profile_manifests/local_vars.yml"

- include: create-configdir.yml

- include: pki-roo-ca.yml

- include: pki-intermediate-ca.yml

- include: pki-cert.yml

- include: ssh-pki.yml

- include: cord_profile.yml 
