- name: Ensuring config directories exist
  become: true
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    mode: "0770"
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ consul_services }}"

- name: Copying over consul configuration
  become: true
  vars:
    service: "{{ consul_services['consul-server'] }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ node_config_directory }}/consul-server/{{ item.dest }}"
    mode: "0660"
  register: consul_server_confs
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  with_items:
    - { src: "consul-server.conf.j2", dest: "consul-server.conf" }
  notify:
    - Restart consul-server container

- name: Check consul containers
  become: true
  kolla_docker:
    action: "compare_container"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    pid_mode: "{{ item.value.pid_mode|default('') }}"
    ipc_mode: "{{ item.value.ipc_mode|default(omit) }}"
    privileged: "{{ item.value.privileged|default(False) }}"
    volumes: "{{ item.value.volumes|reject('equalto', '')|list }}"
  register: check_consul_containers
  when:
    - action != "config"
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ consul_services }}"
  notify:
    - "Restart {{ item.key }} container"
