- include: add-onboard-containers-playbook.yml

- name: Check XOS Ready
  hosts: head
  connection: docker
  roles:
    - xos-ready

- name: Apply profile config
  hosts: xos_ui
  connection: docker
  roles:
    - xos-config

- name: Include vars
  hosts: config
  tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_items:
        - "profile_manifests/{{ cord_profile }}.yml"
        - profile_manifests/local_vars.yml

- name: Apply profile config (new engine)
  hosts: head
  roles:
    - xos-config-new-tosca
